# Generated by Django 4.2.7 on 2024-10-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgges/')),
            ],
        ),
        migrations.AlterField(
            model_name='offre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imgges/'),
        ),
    ]
